
image: Visual Studio 2017
version: 1.0.{build}
build_script:
- ps: >-
    dotnet restore HardHat.sln --source https://api.nuget.org/v3/index.json
        dotnet build HardHat.sln
        if($env:APPVEYOR_REPO_TAG -eq "true")
        {
          dotnet pack src\HardHat\HardHat.csproj --configuration Release --output ..\..\output /p:Version=$env:APPVEYOR_REPO_TAG_NAME
        }
        else
        {
          dotnet pack src\HardHat\HardHat.csproj --configuration Release --output ..\..\output /p:Version=0.0.1-build-$env:APPVEYOR_BUILD_NUMBER
        }
test_script:
- ps: dotnet test src\HardHat.UnitTests\HardHat.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
artifacts:
- path: output\**.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: //tKHlb2yqAtpxnR6p9IAtXwQNaq8UYYyIFSD0QVF3XnEasIxG2gTWdmWuG87fUX
  on:
    appveyor_repo_tag: true